import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import "./globals.css";

const myFont = Nunito_Sans({
  subsets: ["latin"],
  weight: ["300", "600", "800"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={myFont.className}>{children}</body>
    </html>
  );
}
